language: python

python:
    - "2.6"
    - "2.7"

#env:
#    - COMPILER="gfortran"

# cannot pip install cvxopt==1.1.5
# https://groups.google.com/forum/?fromgroups=#!topic/cvxopt/4PpEfGOoaA0
# apt-get install it instead
before_install:
    - sudo apt-get install libfreetype6-dev
    - sudo apt-get install gfortran liblapack-dev
    - sudo apt-get build-dep python-cvxopt && sudo apt-get install python-cvxopt
    - sudo apt-get install python-qt4
    - sudo apt-get install libatlas-base-dev libatlas3gf-base
    - sudo apt-get install python-numpy

install:
    - pip install --use-mirrors -r requirements.txt
    - pip install --use-mirrors -r requirements-test.txt
    - python setup.py install

script:
  - rake lint
  - nosetests tests/unit tests/integration
